---
title: "R Notebook"
output: html_notebook
---
# Make readble gtf file in R
```{r}
if(!require("rtracklayer")) BiocManager::install("rtracklayer") 
gtf1 <- rtracklayer::import("Homo_sapiens.GRCh38.104.chr.gtf")
gtf_df <- as.data.frame(gtf1)
```


```{r}
save(gtf_df,file = "gtf_df.Rdata")
```

# Use AnnotationDbi package to do ID transfer
```{r}
get_map = function(input) {
  if (is.character(input)) {
    if(!file.exists(input)) stop("Bad input file.")
    message("Treat input as file")
    input = data.table::fread(input, header = FALSE)
  } else {
    data.table::setDT(input)
  }
  
  input = input[input[[3]] == "gene", ]
  
  pattern_id = ".*gene_id \"([^;]+)\";.*"
  pattern_name = ".*gene_name \"([^;]+)\";.*"
  
  
  gene_id = sub(pattern_id, "\\1", input[[9]])
  gene_name = sub(pattern_name, "\\1", input[[9]])
  
  Ensembl_ID_TO_Genename <- data.frame(gene_id = gene_id,
                                        gene_name = gene_name,
                                        stringsAsFactors = FALSE)
  return(Ensembl_ID_TO_Genename)
}
```
```{r}
Ensembl_ID_TO_Genename <- get_map("gencode.v29.annotation.gtf") 


```

```{r}
gtf_Ensembl_ID <- substr(Ensembl_ID_TO_Genename[,1],1,15)
Ensembl_ID_TO_Genename <- data.frame(gtf_Ensembl_ID,Ensembl_ID_TO_Genename[,2])
```
```{r}

colnames(Ensembl_ID_TO_Genename) <- c("Ensembl_ID","gene_id")

```
```{r}
write.csv(Ensembl_ID_TO_Genename,file = "Ensembl_ID_TO_Genename.csv")
```
```{r}
expr_lo_ensg <- expr_df_smallgroup_nopint
colnames(expr_lo_ensg)[1] <- "Ensembl_ID"
```

```{r}
mergeLo <- merge(Ensembl_ID_TO_Genename,expr_lo_ensg,by="Ensembl_ID")
```
```{r}
expr_duct_ensg <- expr_df_biggroup_nopint
colnames(expr_duct_ensg)[1] <- "Ensembl_ID"
mergeDuct <- merge(Ensembl_ID_TO_Genename,expr_duct_ensg,by="Ensembl_ID")
```
```{r}
save(mergeLo,file="mergeLo.Rdata")
save(mergeDuct,file="mergeDu.Rdata")
```
```{r}
mergeLoSeq <- mergeLo[order(mergeLo[,"gene_id"]),]
index<-duplicated(mergeLoSeq$gene_id)
mergeLoSeq <- mergeLoSeq[!index,]
rownames(mergeLoSeq) <-mergeLoSeq[,"gene_id"]
Lo_Counts_expMatrix <- mergeLoSeq[,-c(1:2)]
write.csv(Lo_Counts_expMatrix,file = "Lo_Counts_expMatrix.csv")
```

```{r}
mergeDuctSeq <- mergeDuct[order(mergeDuct[,"gene_id"]),]
index<-duplicated(mergeDuctSeq$gene_id)
mergeDuctSeq <- mergeDuctSeq[!index,]
rownames(mergeDuctSeq) <-mergeDuctSeq[,"gene_id"]
Duct_Counts_expMatrix <- mergeDuctSeq[,-c(1:2)]
write.csv(Duct_Counts_expMatrix,file = "Duct_Counts_expMatrix.csv")
```

